version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo-cont
    ports:
      - '27016:27017'
    networks:
      - fs-app
    
  backend:
    image: 886436962079.dkr.ecr.ap-south-1.amazonaws.com/fullstack-testing:backend
    build: ./backend
    container_name: node-app-cont
    ports:
      - '8001:8000'
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:27017/ums
    networks:
      - fs-app

  frontend:
    image: 886436962079.dkr.ecr.ap-south-1.amazonaws.com/fullstack-testing:frontend
    build: ./frontend
    container_name: react-app-cont
    ports:
      - '5172:5173'
    environment:
    - VITE_API_BASE_URL=http://localhost:8001
    networks:
      - fs-app
    
networks:
  fs-app:
    driver: bridge